name: release Linux

on:
  workflow_dispatch:
    inputs:
      release_tag:
        required: false
        type: string
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

env:
  OutputArch: "linux-64"
  OutputArchArm: "linux-arm64"
  OutputPath64:  "${{ github.workspace }}/v2rayN/Release/linux-64"
  OutputPathArm64:  "${{ github.workspace }}/v2rayN/Release/linux-arm64"

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
      with:
        submodules: 'recursive'
        fetch-depth: '0'

    - name: Setup
      uses: actions/setup-dotnet@v5.0.0
      with:
        dotnet-version: '8.0.x'

    - name: Determine release tag
      id: release_tag
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          echo "tag=${{ github.event.inputs.release_tag }}" >> $GITHUB_OUTPUT
        elif [ "${{ github.ref_type }}" == "tag" ]; then
          echo "tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
        else
          echo "tag=" >> $GITHUB_OUTPUT
        fi
        echo "Release tag: $(cat $GITHUB_OUTPUT | grep tag= | cut -d= -f2)"

    - name: Build
      run: |
        cd v2rayN 
        dotnet publish ./v2rayN.Desktop/v2rayN.Desktop.csproj -c Release -r linux-x64   --self-contained=true -o $OutputPath64
        dotnet publish ./v2rayN.Desktop/v2rayN.Desktop.csproj -c Release -r linux-arm64 --self-contained=true -o $OutputPathArm64
        dotnet publish ./AmazTool/AmazTool.csproj             -c Release -r linux-x64   --self-contained=true -p:PublishTrimmed=true -o $OutputPath64
        dotnet publish ./AmazTool/AmazTool.csproj             -c Release -r linux-arm64 --self-contained=true -p:PublishTrimmed=true -o $OutputPathArm64

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4.6.2
      with:
        name: v2rayN-linux
        path: |
          ${{ github.workspace }}/v2rayN/Release/linux*

    # release debian package
    - name: Package debian
      if: steps.release_tag.outputs.tag != ''
      run: |
        chmod 755 package-debian.sh
        ./package-debian.sh $OutputArch $OutputPath64 ${{ steps.release_tag.outputs.tag }}
        ./package-debian.sh $OutputArchArm $OutputPathArm64 ${{ steps.release_tag.outputs.tag }}

    - name: Upload deb to release
      uses: svenstaro/upload-release-action@v2
      if: steps.release_tag.outputs.tag != ''
      with:
        file: ${{ github.workspace }}/v2rayN*.deb
        tag: ${{ steps.release_tag.outputs.tag }}
        file_glob: true
        prerelease: true

    - name: Package AppImage
      if: steps.release_tag.outputs.tag != ''
      run: |
        chmod a+x package-appimage.sh
        ./package-appimage.sh

    - name: Upload AppImage to release
      uses: svenstaro/upload-release-action@v2
      if: steps.release_tag.outputs.tag != ''
      with:
        file: ${{ github.workspace }}/v2rayN*.AppImage
        tag: ${{ steps.release_tag.outputs.tag }}
        file_glob: true
        prerelease: true

    # release zip archive
    - name: Package release zip archive
      if: steps.release_tag.outputs.tag != ''
      run: |
        chmod 755 package-release-zip.sh
        ./package-release-zip.sh $OutputArch $OutputPath64
        ./package-release-zip.sh $OutputArchArm $OutputPathArm64
    
    - name: Upload zip archive to release
      uses: svenstaro/upload-release-action@v2
      if: steps.release_tag.outputs.tag != ''
      with:
        file: ${{ github.workspace }}/v2rayN*.zip
        tag: ${{ steps.release_tag.outputs.tag }}
        file_glob: true
        prerelease: true

    # release RHEL package
    - name: Package RPM (RHEL-family)
      if: steps.release_tag.outputs.tag != ''
      run: |
        chmod 755 package-rhel.sh
        # Build for both x86_64 and aarch64 in one go (explicit version passed; no --buildfrom)
        ./package-rhel.sh "${{ steps.release_tag.outputs.tag }}" --arch all

    - name: Collect RPMs into workspace
      if: steps.release_tag.outputs.tag != ''
      run: |
        mkdir -p "${{ github.workspace }}/dist/rpm"
        rsync -av "$HOME/rpmbuild/RPMS/" "${{ github.workspace }}/dist/rpm/"
        # Rename to requested filenames
        find "${{ github.workspace }}/dist/rpm" -name "v2rayN-*-1.x86_64.rpm" -exec mv {} "${{ github.workspace }}/dist/rpm/v2rayN-linux-rhel-x64.rpm" \; || true
        find "${{ github.workspace }}/dist/rpm" -name "v2rayN-*-1.aarch64.rpm" -exec mv {} "${{ github.workspace }}/dist/rpm/v2rayN-linux-rhel-arm64.rpm" \; || true

    - name: Upload RPM artifacts
      if: steps.release_tag.outputs.tag != ''
      uses: actions/upload-artifact@v4.6.2
      with:
        name: v2rayN-rpm
        path: |
          ${{ github.workspace }}/dist/rpm/**/*.rpm

    - name: Upload RPMs to release
      uses: svenstaro/upload-release-action@v2
      if: steps.release_tag.outputs.tag != ''
      with:
        file: ${{ github.workspace }}/dist/rpm/**/*.rpm
        tag: ${{ steps.release_tag.outputs.tag }}
        file_glob: true
        prerelease: true
